data_dir: /home/miyashita/gitrepo/LieFlow/data/
expdim: 16
layersize: 4
var: 1.
batch_size: 1000
logger:
  name: test_lieflow
  save_dir: logs/lightning_logs
  default_hp_metric: false
trainer:
  max_epochs: 10
  gpus: 1

hydra:
  run:
    dir: ./
  sweep:
    dir: ./
    subdir: ./
  # sweeper:
  #   params:
  #     optim.optimizer: SGD,Adadelta,Adam
  #     optim.lr: 1.0e-4,1.0e-3,1.0e-2
